# User's block
- block:
  - name: "Get home directory for user '{{ USER }}'"
    shell: "echo $HOME"
    register: home
  - name: Create NGINX cache direcotry
    file:
      path: "{{ home.stdout }}/.cache/nginx"
      mode: 0755
      state: directory
  become: yes
  become_user: "{{ USER }}"
  become_method: sudo
  become_flags: "-i"

# RPM Packages
- block:
  - name: Install nginx.org repo
    yum:
      name: "http://nginx.org/packages/centos/{{ ansible_distribution_major_version }}/noarch/RPMS/nginx-release-centos-{{ ansible_distribution_major_version }}-0.el{{ ansible_distribution_major_version }}.ngx.noarch.rpm"
      state: present
  - name: Install NGINX
    yum:
      name: "nginx,nginx-module-image-filter"
      state: latest
  when: ansible_pkg_mgr == "yum"

# DEB Packages
- block:
  - name: Requested packages install (DEB)
    apt:
      name: "nginx"
      state: latest
  when: ansible_pkg_mgr == "apt"
