#!/bin/bash

STATUSDIR="/var/run/smartd"
STATUSFILE="${SMARTD_DEVICESTRING#/dev/}"; STATUSFILE="${STATUSFILE//\//#}"

mkdir -p "$STATUSDIR"

cat <<EOF > "$STATUSDIR/$STATUSFILE"
DEVICE='$SMARTD_DEVICE'
DEVICEINFO='$SMARTD_DEVICEINFO'
DEVICESTRING='$SMARTD_DEVICESTRING'
DEVICETYPE='$SMARTD_DEVICETYPE'
FAILTYPE='$SMARTD_FAILTYPE'
EOF
