---
- hosts: all
  roles:
    - role: elasticsearch
  remote_user: root
  vars:
    update: true
    es:
      user: "elastic"
      password: "ImHabUgtydtetic5"
      plugins:
        #- "x-pack"
        - "ingest-geoip"
        - "ingest-user-agent"
    kibana:
      #plugins:
      #  - "x-pack"
#  vars_prompt:
#    - name: "update"
#      prompt: "Update only?"
#      default: true
#      private: no
